name: Deploy to Strato Webspace via SFTP

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: SFTP uploader
        # You may pin to the exact commit or the version.
        # uses: wangyucode/sftp-upload-action@0ce8147ad8637906ceb7ebb272640ca45e4b2b31
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 22
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          localDir: ./src/
          remoteDir: /
                
